### ISSUE TITLE
Crash after being put to sleep

### ISSUE THREAD

**Issue by blindman2k** [nightrune/wrench#52]
I closed my laptop without shutting down wrench logs ... it wasn't too happy about that.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x407c6aa]

goroutine 1 [running]:
github.com/nightrune/wrench/ei.(*BuildClient)._complete_request(0xc20801e500, 0x4335530, 0x3, 0xc2082cf110, 0x65, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /Users/me/Sites/go.home/src/github.com/nightrune/wrench/ei/ei.go:163 +0x21a
github.com/nightrune/wrench/ei.(*BuildClient).ContinueDeviceLogs(0xc20801e500, 0xc208229180, 0x47, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/me/Sites/go.home/src/github.com/nightrune/wrench/ei/ei.go:458 +0x16e
main.StartDeviceLogging(0xc20801e500, 0x7fff5fbffbf9, 0x10)
    /Users/me/Sites/go.home/src/github.com/nightrune/wrench/device.go:49 +0x52b
main.DeviceSubCommand(0x44b0ca0, 0xc20800a010, 0x3, 0x3)
    /Users/me/Sites/go.home/src/github.com/nightrune/wrench/device.go:122 +0x466
main.main()
    /Users/me/Sites/go.home/src/github.com/nightrune/wrench/wrench.go:209 +0xa39

goroutine 5 [syscall, 148 minutes]:
os/Signal.loop()
    /opt/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/Signal.init·1
    /opt/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [chan receive, 148 minutes]:
main.func·004()
    /Users/me/Sites/go.home/src/github.com/nightrune/wrench/wrench.go:187 +0x55
created by main.main
    /Users/me/Sites/go.home/src/github.com/nightrune/wrench/wrench.go:191 +0x353

goroutine 17 [syscall, 148 minutes, locked to thread]:
runtime.goexit()
    /opt/local/go/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by nightrune** [comment]
Do you know what signals are sent from sleep? I'm not even sure where I can start with this.

**Comment by blindman2k** [comment]
I know naaasing.
